on:
  push:
    branches:
      - main
name: Build and Deploy
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP.SERVER: ${{ secrets.FTP.SERVER }}
          FTP.USERNAME: ${{ secrets.FTP.USERNAME }}
          FTP.PASSWORD: ${{ secrets.FTP.PASSWORD }}
          LOCAL_DIR: ./
          REMOTE_DIR: "/2025/makuraya"
